manheim/terraform-pipeline

CHANGELOG.md, docs/S3BackendPlugin.md, src/S3BackendPlugin.groovy, test/S3BackendPluginTest.groovy
* encrypt - (Optional) Whether to enable server side encryption of the
state file.
* kms_key_id - (Optional) The ARN of a KMS Key to use for encrypting the
state.
=> S3BackendPlugin - encrypt & kms_key_id options

CHANGELOG.md, README.md, docs/TfvarsFilesPlugin.md, src/TerraformPlanCommand.groovy, src/TfvarsFilesPlugin.groovy, test/TerraformPlanCommandTest.groovy, test/TfvarsFilesPluginTest.groovy
This plugin allows you to add environment specific tfvars files to your plan and apply commands.
This required adding the `withArgument('-some-arg')` pattern to the `TerraformPlanCommand` to support this.
Documentation has been added and linked in the Readme.
=> (Feature) Add TfvarsFilesPlugin.

.travis.yml, CHANGELOG.md, README.md, src/CrqPlugin.groovy, src/FileParametersPlugin.groovy, src/S3BackendPlugin.groovy, test/CrqPluginTest.groovy, test/FileParametersPluginTest.groovy, test/S3BackendPluginTest.groovy
* Run unit tests through travis CI
* Tests have been refactored - TravisCI uncovered subtle problems with the unit tests
* Global variables  `Jenkinsfile.instance`  are being modified, and affecting subsequent tests.  Let's walk away from modifying global variables all  together while writing unit tests.
=> Issue 87: run tests through travis CI

CHANGELOG.md, codecov.yml, src/Jenkinsfile.groovy, src/TerraformPlugin.groovy, test/TerraformPluginTest.groovy
* Issue #186 
* UseCase: I want to use the `agent` block to pull a docker image that contains the terraform executable that matches my project's version.  Allow me to conveniently detect the terraform version so that I pull the correct docker image.
* Example: 
```
Jenkinsfile.init(this)
def terraformVersion = TerraformPlugin.checkVersion()
AgentNodePlugin.withAgentDockerImage("hashicorp/terraform:${terraformVersion}")
.withAgentDockerImageOptions("--entrypoint=''")
.init()
...
```
=> Issue 186: convenience method to detect terraform version

CHANGELOG.md, src/Jenkinsfile.groovy
* Newer versions of  "Pipeline: Groovy" confuse the multiple `Jenkinsfile.init` methods.
* The `Jenkinsfile.init(this,env)` method is deprecated - drop support  for this method to solve the  problem.
* Anyone using the deprecated `Jenkinsfile.init(this,env)` method should simply  stop passing the `env` parameter
=> Issue 196: Fix defect - Excessive nested closures in Jenkinsfile.init

CHANGELOG.md, src/BuildStage.groovy, src/Jenkinsfile.groovy, src/RegressionStage.groovy, src/StageDecorations.groovy, src/TerraformEnvironmentStage.groovy, src/TerraformValidateStage.groovy, test/BuildStageTest.groovy, test/RegressionStageTest.groovy, test/StageDecorationsTest.groovy, vars/ApplyJenkinsfileClosure.groovy
* Don't override `node` in Jenkinsfile to control the node label - be explicit
* Stop using invokeMethod in Jenkinsfile, execute DSL within the context of Jenkinsfile using `ApplyJenkinsfileClosure`
* Stop copy-paste of Stage decorations - delegate behavior to new `StageDecorations`
* Fix CPS mismatch errors that show up in latest pipeline plugins.
=> Issue 151 - Fix CPS mismatch errors, reduce meta magic in Jenkinsfile.groovy and Stage decorations

test/StageDecorationsTest.groovy
* Cleanup tests only for issue #151
=> Issue 151 - test cleanup

CHANGELOG.md, docs/TfvarsFilesPlugin.md, src/BuildStage.groovy, src/Jenkinsfile.groovy, src/RegressionStage.groovy, src/StageDecorations.groovy, src/TerraformEnvironmentStage.groovy, src/TerraformValidateStage.groovy, src/TfvarsFilesPlugin.groovy, test/BuildStageTest.groovy, test/RegressionStageTest.groovy, test/StageDecorationsTest.groovy, test/TerraformEnvironmentStageTest.groovy, test/TfvarsFilesPluginTest.groovy, vars/ApplyJenkinsfileClosure.groovy
* [Issue #151](https://github.com/manheim/terraform-pipeline/issues/151) Fix CPS mismatch errors, reduce meta magic in Jenkinsfile.groovy and Stage decorations
* [Issue #194](https://github.com/manheim/terraform-pipeline/issues/194) Add support global tfvars files.
* [Issue #198](https://github.com/manheim/terraform-pipeline/issues/198) Fix using only TerraformEnvironmentStages
* [Issue #196](https://github.com/manheim/terraform-pipeline/issues/196) Fix defect - Excessive nested closures in Jenkinsfile.init.  Drop support for deprecated `Jenkinsfile.init(this,env)`
=> Create v5.5 Release

CHANGELOG.md, src/TerraformApplyCommand.groovy, src/TerraformPlanCommand.groovy, src/TerraformValidateCommand.groovy, test/TerraformApplyCommandTest.groovy, test/TerraformInitCommandTest.groovy, test/TerraformPlanCommandTest.groovy, test/TerraformValidateCommandTest.groovy
* Issue #221 added suffix support for terraform init, but this functionality is useful for all terraform commands
* Add suffix support to all terraform commands.
=> Support suffixes for *ALL* terraform commands

CHANGELOG.md, README.md, docs/TargetPlugin.md, src/TargetPlugin.groovy, test/TargetPluginTest.groovy
Implementation for https://github.com/manheim/terraform-pipeline/issues/102
Supporting the `-target` parameter via Build Parameters.
=> Support target for plan/apply

CHANGELOG.md, README.md
* Issue #206 
* Explain the importance of plugin order, using pure-plugins as an example
* This is meant to push PR #220 along
=> Issue 206: Explain the importance of plugin order

CHANGELOG.md, vars/Pipeline2Stage.groovy, vars/Pipeline3Stage.groovy, vars/Pipeline4Stage.groovy, vars/Pipeline5Stage.groovy, vars/Pipeline6Stage.groovy, vars/Pipeline7Stage.groovy
* Issue #218 
* use preserveStage by default in declarative templates
* Default preserveStage behavior stashes only a single stash (See: https://www.jenkins.io/doc/book/pipeline/running-pipelines/)
=> Issue 218: preserveStash in default declarative templates

CHANGELOG.md, docs/AgentNodePlugin.md, src/AgentNodePlugin.groovy, test/AgentNodePluginTest.groovy, test/DummyJenkinsfile.groovy
This supersedes and continues the work from PR #231 
* Make fixes from PR above
* Simplify the README - don't include unrelated plugins
* Dockerfile should use fluent programming conventions
* Do not hardcode 'Dockerfile' file name - default, but allow it to be overridden
* Add tests
=> Support building dockerfile & fix Terraform PR args (supersedes)

CHANGELOG.md, src/TerraformPlanResultsPRPlugin.groovy
*  TerraformPlanPRResultsPlugin adds an out file parameter, which conflicts with the  DirectoryPlugin during `terraform plan`
* `-out=tfplan` is a terraform plan argument and  should use `withArgument` to preserve the correct argument order.
=> Issue 232: PRPlugin breaks when using DirectoryPlugin

CHANGELOG.md, README.md, docs/GithubPRPlanPlugin.md, docs/TerraformPlanResultsPRPlugin.md, src/GithubPRPlanPlugin.groovy, src/Jenkinsfile.groovy, src/TerraformPlanCommand.groovy, src/TerraformPlanResultsPRPlugin.groovy, test/DummyJenkinsfile.groovy, test/GithubPRPlanPlugin.groovy, test/JenkinsfileTest.groovy, test/TerraformPlanCommandTest.groovy, test/TerraformPlanResultsPRPluginTest.groovy
* More for Issue #193 
* Repo slug can be constructed from the scm URL
* The base URL can be constructed from the scm URL
* Remove landscape functionality from the plugin - there's a separate Landscape plugin
=> Issue 193: Simplify implementation

CHANGELOG.md
This was a miss in PR #273, and should have been part of issue #272
=> Update CHANGELOG for BuildWithParametersPlugin

CHANGELOG.md, README.md
=> Realphabetize the Plugins in README

CHANGELOG.md, src/ConfirmApplyPlugin.groovy, src/DestroyPlugin.groovy, test/ConfirmApplyPluginTest.groovy, test/DestroyPluginTest.groovy
* This closes #261, and builds on the original Issue #88 
* Require the user to type in  something to confirm that they want to destroy, it make it more difficult to make a mistake
=> Issue 261: Require user to type in confirmation for destroy

docs/GithubPRPlanPlugin.md, src/GithubPRPlanPlugin.groovy, test/GithubPRPlanPlugin.groovy
See https://github.com/manheim/terraform-pipeline/issues/254
=> Issue #254: GithubPlanPR bug fix

CHANGELOG.md, src/TagPlugin.groovy, src/TerraformApplyCommand.groovy, src/TerraformPlanCommand.groovy, src/TerraformPlugin.groovy, src/TerraformPluginVersion.groovy, src/TerraformPluginVersion12.groovy, test/DummyJenkinsfile.groovy, test/TagPluginTest.groovy, test/TerraformApplyCommandTest.groovy, test/TerraformPlanCommandTest.groovy, test/TerraformPluginTest.groovy, test/TerraformPluginVersion11Test.groovy, test/TerraformPluginVersion12Test.groovy
* Issue #289 
* the syntax for passing variables through the CLI changed between 0.11.x and 0.12.x
* Fix the TagPlugin so that it automatically works with either version.
=> Issue 289: TagPlugin should work with both v11 and v12

CHANGELOG.md, README.md, docs/TerraformEnvironmentStage.md
=> added docs on withEnv & withGlobalEnv

CHANGELOG.md, README.md, docs/PassPlanFilePlugin.md, src/ConditionalApplyPlugin.groovy, src/PassPlanFilePlugin.groovy, test/DummyJenkinsfile.groovy, test/PassPlanFilePluginTest.groovy
=> Issue 175: Pass terraform plan file to apply

CHANGELOG.md, docs/TagPlugin.md, src/TagPlugin.groovy, test/TagPluginTest.groovy
* When you use a plan file, terraform apply will error if you pass variables on the CLI
* Allow variables to be skipped on apply, to allow for the use of plan files.
=> Issue 296: Optionally disable CLI variables on apply

CHANGELOG.md, src/TerraformPlugin.groovy, test/TerraformPluginTest.groovy
* This was a regression, introduced by v5.12
* I was attempting to refactor and conslidate the duplicate readFile logic, and used the wrong method.
=> Issue 300: Trim whitespace when detecting terraform version from file

CHANGELOG.md, docs/ParameterStoreBuildWrapperPlugin.md, src/ParameterStoreBuildWrapperPlugin.groovy, test/ParameterStoreBuildWrapperPluginTest.groovy
* add support for global parameters
=> AWSParameterStore - Support Global Parameters

CHANGELOG.md, test/FileParametersPluginTest.groovy, test/TagPluginTest.groovy
Issue #311 
* Mockito spies use different stub syntax.  `getEnv` should be stubbed, but is getting incorrectly called instead.  Use the correct stubbing syntax so that the underlying method is not called.
* Identify and fix the test that was not cleaning up after itself (Answer: TagPluginTest)
* Fix FileParametersPlugin - it's accessing global environment variables, and therefore expects `Jenkinsfile.original` to be stubbed.
=> Issue #311: non-deterministic test failures

CHANGELOG.md, docs/TerraformEnvironmentStage.md, src/TerraformEnvironmentStage.groovy
This PR adds some more-granular decorators around the shell commands run in TerraformEnvironmentStage (init, plan, and apply). This provides an extension point for a future plugin to allow executing shell commands (hooks) before and/or after each of these commands.
Please note that I have not (yet?) added unit tests for this. As far as I can tell the current code does not have tests for anything in the closure, aside from it not blowing up, and I'm not entirely sure how to test this...
=> Fixes #316 - implement more granular decorations in TerraformEnvironmentStage

CHANGELOG.md, build.gradle
* Issue #321 
* PR #250 has a compile error in travisCI
* Groovy 2.4.12 has a fix for the problem, and solves the failing travisCI builds
=> Issue 321: Upgrade groovy from 2.4.11 to 2.4.12

docs/TerraformEnvironmentStageShellHookPlugin.md
* Issue #250 
* Fix hook point constants `INIT` -> `INIT_COMMAND`, `APPLY` -> `APPLY_COMMAND`
* Fix version in library - default to no version, since we don't want to have to update it all the time
=> Doc Fix: TerraformEnvironmentStageShellHookPlugin typos

CHANGELOG.md, src/ConditionalApplyPlugin.groovy, test/ConditionalApplyPluginTest.groovy
resolves manheim/terraform-pipeline#172
=> Be able to configure conditional branches

CHANGELOG.md, src/Jenkinsfile.groovy, test/AgentNodePluginTest.groovy
* Issue #331 
* How to reproduce: 
* Have a jenkins instance that does not have Docker Pipeline plugin installed
* Load a terraform-pipeline project in Jenkins, and load the library with `Jenkinsfile.init(this)`
* __Expected:__ the pipeline loads with no error
* __Actual:__ the pipeline errors with: 
```
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: docker for class: WorkflowScript
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
at …
```
=> Issue 331: terraform-pipeline should not fail if DockerPipeline plugin not installed

CHANGELOG.md, src/GithubPRPlanPlugin.groovy, test/GithubPRPlanPluginTest.groovy
* Issue #320 
* The Plugin incorrectly swallows plan errors (due to an always-successful `tee` command).
* Fail the pipeline on plan errors, and display the plan results to the user.
* Continue to behave normally if there are no plan errors.
=> Issue 320: Fix bug in GithubPRPlugin, stop pipeline and display error on plan failures.

CHANGELOG.md, docs/PlanOnlyPlugin.md, src/PlanOnlyPlugin.groovy, test/PlanOnlyPluginTest.groovy
* Issue #344 
* Create `PLAN_ONLY` parameter to control skipping `terraform apply`
=> Issue 344: Add PLAN_ONLY parameter to PlanOnlyPlugin

CHANGELOG.md, src/ConfirmApplyPlugin.groovy
When asked to confirm the apply currently it takes you to a page with standard messaging identical for all environments. This PR gives a little more context on which environment your confirming
Closes #318
=> Feature: Show environment on confirm apply page

CHANGELOG.md, docs/TerraformTaintPlugin.md, src/TerraformTaintCommand.groovy, src/TerraformTaintCommandPlugin.groovy, src/TerraformTaintPlugin.groovy, src/TerraformUntaintCommand.groovy, src/TerraformUntaintCommandPlugin.groovy, test/TerraformTaintCommandTest.groovy, test/TerraformTaintPluginTest.groovy, test/TerraformUntaintCommandTest.groovy
The `TerraformTaintPlugin` adds new parameters to a build for resources to taint / untaint. If nothing is specified, then the plugin does nothing. If a value is provided in one of the parameters, then the corresponding command will be ran prior to the `terraform plan` command. It also includes support for restricting the execution to a given branch or set of branches, as well as restricting based the origin repository of the code checked out in the workspace.
```
// Jenkinsfile
@Library(['terraform-pipeline@v3.10']) _
Jenkinsfile.init(this, env)
// This enables the "taint" and "untaint" functionality
// It will only apply to the master branch (default behavior)
// and will only apply if the current worspace code is checked out from the
// MyOrg/myrepo repository. …
```
=> Issue #354: Add taint and untaint command

CHANGELOG.md, README.md, docs/FlywayMigrationPlugin.md, src/FlywayCommand.groovy, src/FlywayMigrationPlugin.groovy, test/FlywayCommandTest.groovy, test/FlywayMigrationPluginTest.groovy
* Issue #21 
* We use terraform-pipeline to manage our databases
* It would be nice to incorporate flyway database migrations into the pipelines that manage our databases
* Create a new plugin to do that.
=> Issue 21: Create plugin to run Flyway database migrations in pipeline

CHANGELOG.md, src/FlywayMigrationPlugin.groovy, test/FlywayMigrationPluginTest.groovy
* Issue #363 
* By default, disable echo for the flyway CLI. (so that username/password is not echoed in Jenkins logs)
* Optionally allow echo to be enabled by the user
=> Optionally enable echo on flyway CLI commands

CHANGELOG.md, docs/FlywayMigrationPlugin.md, src/FlywayCommand.groovy, src/FlywayMigrationPlugin.groovy, test/FlywayCommandTest.groovy, test/FlywayMigrationPluginTest.groovy
* Issue #365 
* Push username/password to FlywayCommand, so they can be passed as CLI parameters
* Add additional generic parameter to FlywayCommand, for all other options.
* Remove username/password environment variable mapping.  Replace with generic variable mapping.
=> Issue 365: Make flyway configuration more generic

CHANGELOG.md, docs/FlywayMigrationPlugin.md, src/FlywayMigrationPlugin.groovy, test/FlywayMigrationPluginTest.groovy
* Issue #368 
* Applying a migration may be an uncommon case - more commonly, no pending migration may exist
* Because this is an uncommon occurrence, a user may not be accustomed to validating during the "plan" stage whether or not a pending migration exists.
* As an extra safe guard, optionally prompt the user *again* if a migration is detected - reconfirm that the user is aware that a pending migration exists, and approves the application of said migration.
* This should be optional
=> Issue 368: Prompt the user *again* if a pending migration is detected.  Optionally disable.

src/TerraformTaintPlugin.groovy
This PR fixes a bug with the TerraformTaintPlugin where the taint or untaint commands would run even if no resources were specified.
=> Fix taint and untaint behavior

CHANGELOG.md, docs/CredentialsPlugin.md, src/CredentialsPlugin.groovy, test/CredentialsPluginTest.groovy, test/MockWorkflowScript.groovy
CredentialsPlugin currently only supports username/password, but there are many more.  Support all types of credential bindings.
=> Issue 214: CredentialsPlugin - support more than username/password

.github/workflows/build.yml, CHANGELOG.md
=> use java11

CHANGELOG.md, src/TerraformApplyCommand.groovy, test/TerraformApplyCommandTest.groovy
If a plan file is being used in the `TerraformApplyCommand`, then the only
applicable Terraform subcommand is `apply`. This PR forces apply to be used if
a plan file is set. This works whether the plan file was created with or without
the `-destroy` argument.
- Force the use of `terraform apply` in TerraformApplyCommand if a planFile is present
- Update changelog
=> [Bugfix] Fixes #417 - Force terraform command to `apply` if a plan file is being used

.gitignore, CHANGELOG.md, src/TerraformApplyCommand.groovy, test/TerraformApplyCommandTest.groovy
- Omit variables and variable files when building apply command and a plan file has been specified
=> Fixes #436 - Omit variables and variable files from apply command when using a plan file

CHANGELOG.md, docs/WithAwsPlugin.md, src/WithAwsPlugin.groovy, test/WithAwsPluginTest.groovy
Work in progress PR to fix #444 by adding an optional `duration` parameter to WithAwsPlugin.withRole().
=> Fixes #444 - Add duration parameter to WithAwsPlugin.withRole()
