manheim/terraform-pipeline

CHANGELOG.md
docs/AwssumePlugin.md

Issue 178: Fix link to AwssumePlugins source code from docs

---

CHANGELOG.md
README.md
docs/AwssumePlugin.md
docs/TerraformPlugin.md
docs/TfvarsFilesPlugin.md
src/Jenkinsfile.groovy
src/SemanticVersion.groovy
src/TerraformInitCommand.groovy
src/TerraformPlanCommand.groovy
src/TerraformPlugin.groovy
src/TerraformPluginVersion.groovy
src/TerraformPluginVersion11.groovy
src/TerraformPluginVersion12.groovy
src/TerraformValidateCommand.groovy
src/TerraformValidateStage.groovy
src/TfvarsFilesPlugin.groovy
test/ConditionalApplyPluginTest.groovy
test/SemanticVersionTest.groovy
test/TerraformInitCommandTest.groovy
test/TerraformPlanCommandTest.groovy
test/TerraformPluginTest.groovy
test/TerraformPluginVersion11Test.groovy
test/TerraformPluginVersion12Test.groovy
test/TfvarsFilesPluginTest.groovy

* Close out v5.3-dev branch, and publish a new release

Create v5.3 Release

---

.travis.yml
build.gradle
codecov.sh

* Part 2  of Issue #87 
* Track and report code coverage with https://codecov.io/

Issue #87: Run jacoco code coverage and send to codecov.io

---

CHANGELOG.md
src/TerraformPlugin.groovy
test/TerraformPluginTest.groovy

* Issue 185: fix defect in `TerraformPlugin.readFile`

 Issue 185: fix defect in TerraformPlugin.readFile

---

CHANGELOG.md
README.md
docs/CredentialsPlugin.md
src/CredentialsPlugin.groovy
src/TerraformEnvironmentStage.groovy
src/TerraformValidateStage.groovy
test/CredentialsPluginTest.groovy

* Issue  #192 
* Previously, the CredentialsPlugin only modified the BuildStage
* Have it also inject credentials into every other Stage (RegressionStage, TerraformEnvironmentStage, TerraformValidateStage).

Apply CredentialsPlugin across all Stages

---

CHANGELOG.md
docs/ParameterStoreBuildWrapperPlugin.md
src/ParameterStoreBuildWrapperPlugin.groovy
test/ParameterStoreBuildWrapperPluginTest.groovy

Allow custom pattern for ParameterStoreBuildWrapperPlugin

---

CHANGELOG.md
README.md
docs/CredentialsPlugin.md
docs/ParameterStoreBuildWrapperPlugin.md
src/CredentialsPlugin.groovy
src/ParameterStoreBuildWrapperPlugin.groovy
src/TerraformEnvironmentStage.groovy
src/TerraformValidateStage.groovy
test/CredentialsPluginTest.groovy
test/ParameterStoreBuildWrapperPluginTest.groovy

* Issue #203 - ParameterStoreBuildWrapperPlugin - allow path to be customized
* Issue #192 - Apply CredentialsPlugins to all Stages, not just BuildStage

Create 5.6 release

---

CHANGELOG.md
README.md
docs/TerraformLandscapePlugin.md
src/TerraformApplyCommand.groovy
src/TerraformInitCommand.groovy
src/TerraformLandscapePlugin.groovy
src/TerraformPlanCommand.groovy
src/TerraformValidateCommand.groovy
test/TerraformApplyCommandTest.groovy
test/TerraformInitCommandTest.groovy
test/TerraformLandscapePluginTest.groovy
test/TerraformPlanCommandTest.groovy
test/TerraformValidateCommandTest.groovy

* Issue #210 Support Terraform Landscape Plugin - Terraform Plan reformatting
* Issue #221 Support suffixes for terraform commands
*  Issue #222 TerraformInitCommand - withPrefix doesn't support multiple prefixes

Publish v5.7 Release

---

CHANGELOG.md
docs/TerraformPlanResultsPR.md
src/TerraformEnvironmentStage.groovy
src/TerraformPlanResultsPR.groovy
src/TerraformPlugin.groovy
test/TerraformPlanResultsPRTest.groovy

Implementation for https://github.com/manheim/terraform-pipeline/issues/193
Added new plugin `TerraformPlanResultsPR` which will comment Terraform plan results as github PR comments.

Support PR plan output to github comments

---

README.md
docs/TerraformPlanResultsPRPlugin.md
src/TerraformPlanResultsPRPlugin.groovy
test/TerraformPlanResultsPRPluginTest.groovy

* Issue 234: rename the plugin to include the word "plugin"

Issue 234: Rename the plugin to be consistent

---

CHANGELOG.md
README.md

* Cannot use the variable `stages` - it causes Jenkinsfile to fail
* change variable name to something else

Issue 219: Fix docs - variable name cannot be stages

---

CHANGELOG.md
README.md

* Issue #225 
* Do away with branches
* Let's just create releases off of master.

Issue 225: Simplify the Contribution Model

---

src/TargetPlugin.groovy
test/DummyJenkinsfile.groovy
test/TargetPluginTest.groovy

Issue 102: Defect - do not use target if not resources given

---

CHANGELOG.md
README.md

* Issue #265 
* Add codecov badge to README

Issue #265: Add codecoverage badge to README

---

src/ParameterStoreBuildWrapperPlugin.groovy
src/ParameterStoreExecPlugin.groovy
src/TerraformEnvironmentStage.groovy

* Issue #88 
* There's some dead code that was missed from the last  PR

Issue #88: Clean up dead code

---

README.md

Fixed links of plugins under Requirements and Assumptions

---

CHANGELOG.md
README.md
docs/TagPlugin.md
src/Jenkinsfile.groovy
src/TagPlugin.groovy
src/TerraformApplyCommand.groovy
src/TerraformCommand.groovy
src/TerraformPlanCommand.groovy
test/JenkinsfileTest.groovy
test/TagPluginTest.groovy

Issue #256: Make it easy to apply "standard tags"

---

README.md
docs/BuildWithParametersPlugin.md
src/BuildStage.groovy
src/BuildWithParametersPlugin.groovy
src/DecoratableStage.groovy
src/Jenkinsfile.groovy
src/PlanOnlyPlugin.groovy
src/RegressionStage.groovy
src/TargetPlugin.groovy
src/TerraformEnvironmentStage.groovy
src/TerraformValidateStage.groovy
test/BuildWithParametersPluginTest.groovy
test/JenkinsfileTest.groovy
test/PlanOnlyPluginTest.groovy
test/TargetPluginTest.groovy
test/TerraformValidateCommandTest.groovy

* Issue #272  - start refactoring "Build with Parameters" functionality into a  plugin
* This builds on the work done in Issue #162 (boolean plan-only input), and Issue #102 (string target input)
* This should fix defect in Issue  #274

Issue #272: refactor parameters into a plugin

---

CHANGELOG.md
docs/ValidateFormatPlugin.md

* Issue #303 - fix code example, and spelling errors in plugin documentation.

Fix documentation errors for ValidateFormatPlugin

---

CHANGELOG.md
docs/ConditionalApplyPlugin.md
src/ConditionalApplyPlugin.groovy
test/ConditionalApplyPluginTest.groovy

* Issue #329 
* "Confirm"/"Apply" can be enabled on any branch/PR by disabling the ConditionalApplyPlugin.

Issue 329: ConditionalApplyPlugin - disable to allow apply on any branch

---

CHANGELOG.md
docs/ConditionalApplyPlugin.md
src/ConditionalApplyPlugin.groovy
test/ConditionalApplyPluginTest.groovy

* Issue #172 
* Allow confirm/apply on specific environments, regardless of the branch/PR being run.

Issue 172: ConditionalApplyPlugin - enable Confirm/Apply on specific environments, any branch

---

CHANGELOG.md
src/AnsiColorPlugin.groovy
test/AnsiColorPluginTest.groovy
test/MockWorkflowScript.groovy

* Currently AnsiColorPlugin only works on TerraformEnvironmentStage
* Extend it to also work on TerraformValidateStage.

Issue #362 - Bug Fix: Apply AnsiColorPlugin to TerraformValidate

---

src/GithubPRPlanPlugin.groovy
test/GithubPRPlanPluginTest.groovy

Remove unused tfplan in GithubPrPlugin
Fixes #386

bug(remove unused tfplan)

---

CHANGELOG.md
docs/TerraformImportPlugin.md
src/TerraformImportCommand.groovy
src/TerraformImportCommandPlugin.groovy
src/TerraformImportPlugin.groovy
test/TerraformImportCommandTest.groovy
test/TerraformImportPluginTest.groovy

Partial fix for #280 
This adds a basic TerraformImportPlugin and TerraformImportCommand as an initial cut at implementing the full features of Issue #280.

[Issue #280] Add TerraformImportCommand and TerraformImportPlugin

---

CHANGELOG.md
README.md
docs/TerraformStartDirectoryPlugin.md
src/TerraformStartDirectoryPlugin.groovy
test/TerraformStartDirectoryPluginTest.groovy

* https://github.com/manheim/terraform-pipeline/issues/309

TerraformStartDirectoryPlugin - Change the starting execution workspace directory

---

.github/pull_request_template.md
CHANGELOG.md

* Common tasks for a pull request should be made more clear to contributors
* Let's create a checklist on every pull request, so that a contributor knows that they've done everything needed.

Issue 399: Add pull requests templates with a checklist

---

CHANGELOG.md

Update CHANGELOG for Release v5.19

---

.gitignore
CHANGELOG.md
README.md
docs/AnsiColorPlugin.md
docs/ConditionalApplyPlugin.md
docs/CredentialsPlugin.md
docs/ParameterStoreBuildWrapperPlugin.md
docs/TerraformTaintPlugin.md
src/ConditionalApplyPlugin.groovy
src/RegressionStage.groovy
src/TerraformTaintPlugin.groovy
test/ConditionalApplyPluginTest.groovy
test/GithubPRPlanPluginTest.groovy
test/TerraformTaintPluginTest.groovy

This change replaces `master` with `main` in both code and textual references.
It also updates references to `master` and `slave` in text.

Fixes #372 - Change default branch from `master` to `main`

---

CHANGELOG.md

Updating CHANGELOG for v5.20.0 Release
